import { Parisienne,Great_Vibes,Pacifico,Satisfy,Playfair_Display} from "next/font/google";
import {Bonheur_Royale} from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


const satisfy
  = Satisfy({
    variable: "--font-satisfy",
    weight: "400",
    subsets: ["latin"],
  });
const pacifico = Pacifico({
  variable: "--font-pacifico",
  weight: "400",
  subsets: ["latin"],
});
const parisienne = Parisienne({
  variable: "--font-parisienne",
  weight: "400",
  subsets: ["latin"],
});

const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  weight: "400",
  subsets: ["latin"],
});

const bonheurRoyale = Bonheur_Royale({
  variable: "--font-bonheur-royale}",
  weight: "400",
  subsets: ["latin"],
});

const playfairDisplay= Playfair_Display({
  variable: "--font-playfair-display",
  weight: "500",
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${playfairDisplay.variable}${satisfy.variable}${pacifico.variable}${parisienne.variable} ${greatVibes.variable} ${bonheurRoyale.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
