import { Satisfy, Montserrat, Playfair_Display } from "next/font/google";

import "./globals.css";

const satisfy = Satisfy({
  variable: "--font-satisfy",
  weight: "400",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${satisfy.variable} ${montserrat.variable} ${playfair.variable} antialiased mesh-bg smooth-scroll`}
      >
        {children}
      </body>
    </html>
  );
}
