import { Parisienne, Great_Vibes, Pacifico, Satisfy, Montserrat, Playfair_Display } from "next/font/google";

import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


const satisfy
  = Satisfy({
    variable: "--font-satisfy",
    weight: "400",
    subsets: ["latin"],
  });
const pacifico = Pacifico({
  variable: "--font-pacifico",
  weight: "400",
  subsets: ["latin"],
});
const parisienne = Parisienne({
  variable: "--font-parisienne",
  weight: "400",
  subsets: ["latin"],
});

const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  weight: "400",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${satisfy.variable} ${pacifico.variable} ${parisienne.variable} ${greatVibes.variable} ${montserrat.variable} ${playfair.variable} antialiased mesh-bg smooth-scroll`}
      >
        {children}
      </body>
    </html>
  );
}
